env:
  browser: true
  es6: true
  greasemonkey: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 2017
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  semi:
    - error
    - always
  no-console:
    - warn
  no-unused-vars:
    - warn
